### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by abb1991** [Kevo-Wallo/prj-rev-bwfs-dasmoto#3]
I thought you had a very successful project overall! Your styling and code organization were both very strong. I have no overall suggestions to improve your code as is, as a side note, can you say when it’s best to use an element/id?. As an additional suggestion to push yourself further, look up Google Fonts and try adding ‘Lobster’ to your main header! Great work and keep it up!

**Comment by Kevo-Wallo** [comment]
Thank you for your feedback! I took upon your challenge and successfully linked the Google Fonts API in the index.html file and added the lobster font to the main header in style.css. I thank you again for the encouragement and the challenge!
